<?php 
define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASSWORD',''); 
define('DB_NAME','ost');
/*define('DB_HOST','localhost');
define('DB_USER','root');
define('DB_PASSWORD',''); 
define('DB_NAME','bd_intelicorpsa');*/
?>